### ISSUE TITLE
Rename Refactoring from Text Editor Does not Change All References

### ISSUE THREAD

**Issue by philip-alldredge** [osate/osate2-core#855] opened 2017-07-12 14:25 UTC
Under certain circumstances, renaming elements using the text editor's refactoring capability does not update all appropriate portions of the model. Updating all portions of the model is critical for the user experience. Renaming from the graphical editor and updating diagram references relies on the same refactoring capability.

- Rename p1::c1 to p1::c1_renamed. Various extends clauses are not renamed:
  - In p1.aadl:
     - extends c1.impl
     - extends c1.impl_ext
  - In p2.aadl:
    - extends p1::c1.impl
    - extends p1::c1.impl_ext_ext
- Rename p1::c1.f1 to f1_renamed.
  - p1::c1_ext_ext.f1 is not renamed

Test Case:

p1.aadl
```
package p1
public
abstract c1
	features
			f1: in feature;
	end c1;
abstract implementation c1.impl
	end c1.impl;
abstract top
	end top;
abstract implementation top.impl
	end top.impl;
abstract implementation c1.impl_ext extends c1.impl
	end c1.impl_ext;
abstract implementation c1.impl_ext_ext extends c1.impl_ext
	end c1.impl_ext_ext;
abstract c1_ext extends c1
	features
			f1: refined to in feature;
	end c1_ext;
abstract implementation c1_ext.ext
	end c1_ext.ext;
abstract implementation c1_ext.ext_ext extends c1_ext.ext
	end c1_ext.ext_ext;
abstract c1_ext_ext extends c1_ext
	features
			f1: refined to in feature;
	end c1_ext_ext;


end p1;
```

p2.aadl
```
package p2
public
with p1;
	p1_c1 renames abstract p1::c1;
	p1_c1_ext renames abstract p1::c1_ext;

	abstract implementation p1_c1.impl
	end p1_c1.impl;
abstract implementation p1_c1.impl2 extends p1::c1.impl
	end p1_c1.impl2;
abstract implementation p1_c1_ext.impl
	end p1_c1_ext.impl;
abstract implementation p1_c1.impl3 extends p1::c1.impl_ext_ext
	end p1_c1.impl3;
end p2;
```

**Comment by lwrage** [comment] 2017-07-18 19:06
See #359, a fix would require meta-model changes.

**Comment by lwrage** [comment] 2017-07-24 13:14
In particular, a subcomponent would need to contain two references, one to the component type and one to the implementation.

**Comment by philip-alldredge** [comment] 2017-07-27 18:18
I also noticed that attempting to refactor rename a subcomponent which is referenced in an applies to clause of a property association results in a "Refactoring introduces a name conflict" problem.

**Comment by lwrage** [comment] 2017-08-17 17:34
duplicate of #359

**Closed by lwrage** 2017-08-17 17:34 UTC
Labels: resolution:duplicate
