### ISSUE TITLE
Allow execution of analysis tools directly on System Implementations (automatically instantiate the system, then run the tool)

### ISSUE THREAD

**Issue by smithdtyler** [osate/osate2-core#904] opened 2017-09-26 01:29 UTC
It seems to me it would be pretty easy to have an “instantiate on analysis” option that triggers a system instantiation whenever a user runs an analysis on a given system implementation. If the user runs multiple analyses without changing the model, then the system would be instantiated the for the first analysis, and the instantiation would be re-used for the second.

Users that don't want to instantiate their model for each analysis execution could still use the instance file, but users that are working in a write model --> run analysis --> edit model --> run analysis loop could be saved a lot of clicks.

**Comment by lwrage** [comment] 2017-09-26 12:06
Duplicate of #841

**Closed** 2017-09-26 12:07 UTC
Labels: resolution:duplicate
