### ISSUE TITLE
Connection validation incorrectly reports missing classifier

### ISSUE THREAD

**Issue by reteprelief** [osate/osate2-core#896] opened 2017-09-05 17:44 UTC
This occurs when a connection end refers to a prototype bound to a classifier rather than a classifier.

```
package ConnectionPrototypeIssue
public
bus internet
end internet;

system attacker
prototypes
	network : bus;
features
	connection : requires bus access network;
end attacker;
system integration
	
end integration;
system implementation integration.attack 
subcomponents
	attacker_internet : system attacker (network => bus internet);
	internet    : bus internet;
connections
	attacker_to_internet : bus access attacker_internet.connection <-> internet;
end integration.attack;
end  ConnectionPrototypeIssue;
```

**Comment by lwrage** [comment] 2017-09-06 08:53
Duplicate of #641

**Closed** 2017-09-06 08:54 UTC
Labels: resolution:duplicate
