### ISSUE TITLE
OSATE does not correctly instantiate properties that are restricted to system implementations

### ISSUE THREAD

**Issue by backesj** [osate/osate2-core#768] opened 2017-01-24 19:01 UTC
Consider the following model and property set:

```
package Test 
public	 
	with Test_Props;

	system test
	end test;
	
	system implementation test.i
		properties
			Test_Props::Test_Prop => true;
	end test.i;
	
end Test;
```
```
property set Test_Props is
	Test_Prop : aadlboolean applies to (system implementation);
end Test_Props;
```

In the instance model for the impelmentation "test.i" the system does not contain the property "Test_Props::Test_Prop". However, if you change the definition of the property set to:

```
property set Test_Props is
	Test_Prop : aadlboolean applies to (system);
end Test_Props;
```
Then the instance model does contain the property.

**Comment by lwrage** [comment] 2017-02-14 21:18
Duplicate of #635

**Closed by lwrage** 2017-02-14 21:18 UTC
Labels: resolution:duplicate
