### ISSUE TITLE
Missing with check

### ISSUE THREAD

**Issue by joeseibel** [osate/osate2-core#545] opened 2015-02-06 19:13 UTC
```
package pkg
public
  abstract a
  features
    p: in data port [ps::const1];
  end a;
end pkg;
```
In the above example, there should be an error indicating that the property set "ps" needs to be included in a with statement.

**Comment by lwrage** [comment] 2015-02-08 00:25
Duplicate of #456

**Closed** 2015-02-08 00:25 UTC
Labels: category:bug, resolution:duplicate
