### ISSUE TITLE
Injector errors break AADL Navigator & Editor in standard oomph deployment

### ISSUE THREAD

**Issue by bisc** [osate/osate2-core#949] opened 2017-11-28 17:25 UTC
**Summary:** I am trying to update my OSATE2 dev build to Eclipse Oxygen, but the standard setup of OSATE2 crashes when I try to open AADL files or use the Navigator. (None of that took place in Eclipse Neon 4.6.3 with OSATE 2.2.2.)

**Setup:** 
- Running linux x64 (Fedora 25). The only seemingly relevant system package is Google Guice version 4.0.
- Get Eclipse Oxygen - Modeling Tools  4.7.1a
- Import the [2.3.0 version](https://raw.githubusercontent.com/osate/osate2-core/2.3.0-RELEASE/osate.releng/osate2.setup) of the oomph script (that requires editing the redirection cmd, but can go with the latest script as well; also no need to get all repos, osate2-core is sufficient to reproduce this bug.)
- Generate the usual infrastructure with the mwe2 script for Aadl2.xtext. 
- Clean all projects, rebuild the workspace. 

(Actually I tried manually installing a minimal set of packages, like xtext 2.12, on a different copy Eclipse Oxygen, and the same errors as below showed up, so I wouldn't blame the oomph script -- this version or in general.)

**Steps to reproduce issues:** 
1. Run org.osate.branding as an Eclipse Application in a fresh/empty workspace. 
2. Open the AADL navigator view. 
3. Open any predefined aadl file in Plugin_Contributions. This leads to the editor crashing with the following trace (null ptr that seems to originate from an injector-populated variable): 
[editor-propertyset-issue-stacktrace.txt](https://github.com/osate/osate2-core/files/1510922/editor-propertyset-issue-stacktrace.txt)
4. Close the Eclipse App and start it again. This leads to a huge stack trace 
[issue-injectors-in-oxygen-stacktrace3.txt](https://github.com/osate/osate2-core/files/1510927/issue-injectors-in-oxygen-stacktrace3.txt) that can be summarized by these excerpts: 
`Error in custom provider, java.lang.NullPointerException [...]
                 com.google.inject.CreationException: Guice creation errors: [...]
                 java.lang.RuntimeException: Failed to create injector fororg.osate.xtext.aadl2.properties.Properties  [...] 
Failed to create injector for org.osate.xtext.aadl2.properties.Properties  [...] 
Failed to create injector for org.osate.xtext.aadl2.Aadl2`
5. The Eclipse App runs, but the AADL navigator is broken and non-interactive, as in this screenshot: 

![issue-with-injectors-in-oxygen-screenshot](https://user-images.githubusercontent.com/281016/33334018-90af9af4-d436-11e7-9b9d-900db915bb0c.png)

I wonder if I missed a necessary manual change in terms of injection when updating to OSATE2.3.0 or Eclipse Oxygen.

**Comment by bisc** [comment] 2017-11-28 21:06
Tried the same build of Oxygen on an older commit (409dc092480eec6ce3c685d8bcaa3496d6c23071, Sep 12), got same erroneous behavior. 

I also know that OSATE commit 274b1ced2 (Jul 31) does NOT have this behavior with Eclipse Neon 4.6.3.

**Comment by lwrage** [comment] 2017-11-29 14:02
What do you mean by "The only seemingly relevant system package is Google Guice version 4.0."?
Also, did you use the eclipse installer to install oxygen as described on osate.org?

**Comment by bisc** [comment] 2017-11-29 15:12
Re Guice, I noticed that my system has 4.0 installed, and the latest version is 4.1. If you all are using 4.1, it is plausible that these issues might be because of 4.0. (It's not trivial for me to update it now, so I didn't experiment.)

I was downloading the modeling tools version directly from [here](https://www.eclipse.org/downloads/packages/eclipse-modeling-tools/oxygen1a) and doing import->oomph->projects into workspace (then I put the oomph file URL from osate.org). Let me try the installer (didn't realize they had one for linux too) and report on that.

**Comment by lwrage** [comment] 2017-11-29 15:21
I'm concerned about the _system package_ part. Xtext uses guice 3.0. You need to make sure that guice 4.0 is not visible to osate, e.g., it shouldn't be installed in jre/lib/ext.

**Comment by lwrage** [comment] 2017-11-29 17:03
The NPE should go away as soon as you close all open editors and create an AADL project.

**Comment by bisc** [comment] 2017-11-29 19:14
Indeed! Whenever the previous session ended without editors, all the behavior is normal. But should I leave any editor open while closing Eclipse, the injector exceptions come up in the next launch. 

Thanks for looking into this. The issue is more isolated than I thought, but I'll still wait to update till this is resolved.

**Comment by lwrage** [comment] 2017-11-30 17:04
As soon as you have an AADL project in the workspace it is no longer necessary to close the editors. The error only occurs when you open a contributed file in an _empty_ workspace.

**Comment by bisc** [comment] 2017-11-30 17:16
That's not the behavior I'm seeing. 

- Restarting Eclipse after closing on a file in a project: 

![npe-nonempty-workspace](https://user-images.githubusercontent.com/281016/33444398-360f633e-d5c8-11e7-8316-5709fe0e1877.png)
- After trying to open AADL navigator in the same Eclipse: 

![npe-nonempty-workspace-aadlnavigator](https://user-images.githubusercontent.com/281016/33444407-3a209f9c-d5c8-11e7-92e6-bec3f52898cb.png)

**Comment by lwrage** [comment] 2017-11-30 18:31
I see a NoClassDefFoundError, so this looks like a different issue.
Does this also happen on a fresh workspace if you create an AADL project before trying to open a contributed aadl file?

**Comment by bisc** [comment] 2017-11-30 20:16
That may or may not be a different issue, but those NoClassDefFounds occurred all the way along the various setups that I've tried. There is a bunch of them in stacktrace3.txt that I've posted in the original issue text. I am pretty used to seeing that with ContributedAadlStorage by now. 

Just tried fresh workspace->create project->create file->open file->close eclipse->open eclipse. Same errors with long exception logs; here's the new tracefile (looks pretty much the same to me) 
[issue-injectors-in-oxygen-stacktrace4.txt](https://github.com/osate/osate2-core/files/1519335/issue-injectors-in-oxygen-stacktrace4.txt)

**Comment by lwrage** [comment] 2017-11-30 22:12
I have a fix for one NPE that causes the text editor to crash when there is no project in the workspace. That's the only issue I could reproduce.
I suspect that your development setup is somehow messed up. You could try to start from scratch: Delete eclipse, workspaces, and maybe also cloned git repos. Delete directories named \*.oomph.* in $HOME/.eclipse/ to get rid of any cached information. Delete the bundle pool $HOME/.p2; or create a new bundle pool in the installer if you have other eclipse installation that use the existing bundle pool. Then run the installation steps again.

**Comment by bisc** [comment] 2017-12-01 20:44
These are good steps, didn't know where cached bundles were. Unfortunately, even with a fresh bundle pool, deleted .eclipse, and a new installer, I'm having the same errors. 

I'm going to try it on a different system and report back. Thanks for your help so far!

**Comment by bisc** [comment] 2017-12-04 17:13
Surprisingly, I managed to reproduce this bug in a completely new OS (Ubuntu 17.04 x64) & hardware setup. Here's how it goes:

1. Download the installer, run the standard installation script. Close all projects other than in osate2-core.
2. Open eclipse, make a project and a file in it, test opening-closing (everything worked well at this point).
3. In osate2-core, do git checkout 2.3.0-RELEASE and git reset --hard.
4. Rebuild grammar artifacts, clean all projects.  
5. After this, the same old errors show up, with opening saved editors and the AADL navigator.
6. Going back to latest develop doesn't help, the errors persist. I'm trying to make fresh workspaces now, with removing bundle pools and oomph cache, and checking out fresh repos, but it doesn't even build now: errors with resolving org.eclipse.jdt.core and several classes (AbstractAadl2SemanticSequencer, AbstractAadl2SyntacticSequencer, AbstractAadl2ProposalProvider). 

I wonder if this procedure would reproduce the errors -- and if there is more external state to the eclipse/osate installation that I'm failing to delete.

**Comment by lwrage** [comment] 2017-12-04 18:32
Are there any changes in the code after rebuilding grammar artifacts in step 4?

**Comment by lwrage** [comment] 2017-12-04 20:14
You cause the issue by closing too many projects. Open at least _org.osate.ge_ and _org.osate.ge.diagram_.

**Comment by bisc** [comment] 2017-12-05 22:08
Wow, you're right! Opened most GE projects and the errors went away, on both platforms.

It is quite surprising though that there is some implicit dependency from core to GE. Perhaps it could be called out in the docs...

Thanks so much for your help! Feel free to close.

**Closed** 2017-12-05 23:16 UTC
Labels: importance:low
