### ISSUE TITLE
Actual_Connection_Binding does not resolve reference correctly

### ISSUE THREAD

**Issue by reteprelief** [osate/osate2-core#646] opened 2015-11-06 21:19 UTC
The reference to mybus cannot be resolved. If the same property association is declared in the properties section with applies to cp it does fine.

	system implementation platform.i
		subcomponents
			pc1: processor pc;
			pc2: processor pc;
			mybus: bus b;
			mypout: process myoutp.i;
			myinp: process myinp.i;
		connections
			cb1: bus access mybus <-> pc1.ba;
			cb2: bus access mybus <-> pc2.ba;
			cp: port mypout.outp -> myinp.inp {Actual_Connection_Binding => (reference(mybus));};
	end platform.i;

**Comment by reteprelief** [comment] 2015-11-06 21:19
[ACBbug.txt](https://github.com/osate/osate2-core/files/29215/ACBbug.txt)

**Comment by lwrage** [comment] 2015-11-09 01:25
Duplicate of #482

**Closed** 2015-11-09 01:25 UTC
Labels: resolution:duplicate
