### ISSUE TITLE
Suprious clean/build errors usually involving standard properties

### ISSUE THREAD

**Issue by stevevestal** [osate/osate2-core#749] opened 2016-10-31 15:27 UTC
It is not uncommon when starting OSATE to find many Problems of the form

Couldn't resolve reference to UnitLiteral 'ms'.	
Couldn't resolve reference to property definition 'Latency'. Property set name may be missing.

Repeated Project Clean... can often resolve this, but the result is nondeterministic.  Sometimes 100 errors occur, sometimes a dozen, and often (but not always) it clears them all.

**Comment by lwrage** [comment] 2016-11-01 11:50
duplicate of #731

**Closed by lwrage** 2016-11-01 11:50 UTC
Labels: resolution:duplicate
