### ISSUE TITLE
Creating an empty annex crashes editor

### ISSUE THREAD

**Issue by backesj** [osate/osate2-core#849] opened 2017-06-27 19:41 UTC
It seems as of OSATE 2.2.2. if you create an empty annex in a file and save it, then the Eclipse editor will crash whenever the file is opened.  You can repeat this bug by creating the following model:

```
package Scratch
public
	annex agree {**
		
	**};
end Scratch;
```
Save the model, and then attempt to open it again in the Eclipse editor.

**Comment by joeseibel** [comment] 2017-06-27 22:36
Duplicate of #816.

**Closed by joeseibel** 2017-06-27 22:36 UTC
